spring.application.name=study-platform
spring.datasource.url=jdbc:postgresql://localhost:5432/study_platform
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update